#!/usr/bin/env python3
"""Port repository instruction files between Codex and Claude Code.

The portable intersection is Markdown project guidance:

    Codex:       AGENTS.md (or AGENTS.override.md)
    Claude Code: CLAUDE.md

Settings, permissions, hooks, and tool policies are deliberately not translated.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path


MARKER = "<!-- rules-port: generated; edit the source file, then rerun -->"
SOURCE_PREFIX = "<!-- rules-port-source: "
SKIP_DIRS = {".git", ".hg", ".svn", "node_modules", "__pycache__"}


@dataclass(frozen=True)
class Conversion:
    source: Path
    destination: Path


def is_generated(text: str) -> bool:
    return text.startswith(MARKER + "\n")


def portable_body(text: str) -> str:
    """Remove our own header so repeated round trips do not stack headers."""
    if is_generated(text):
        text = text[len(MARKER) + 1 :]
        if text.startswith(SOURCE_PREFIX):
            _, _, text = text.partition("\n\n")
    return text


def rendered(source: Path, destination: Path) -> str:
    body = portable_body(source.read_text(encoding="utf-8"))
    relative = os.path.relpath(source, destination.parent)
    return f"{MARKER}\n{SOURCE_PREFIX}{relative} -->\n\n{body}"


def walk(root: Path):
    for directory, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        yield Path(directory), set(filenames)


def discover(root: Path, direction: str) -> tuple[list[Conversion], list[str]]:
    conversions: list[Conversion] = []
    warnings: list[str] = []

    for directory, names in walk(root):
        if direction == "to-claude":
            # In Codex an override file replaces AGENTS.md at the same level.
            source_name = (
                "AGENTS.override.md"
                if "AGENTS.override.md" in names
                else "AGENTS.md" if "AGENTS.md" in names else None
            )
            if source_name:
                if source_name == "AGENTS.override.md" and "AGENTS.md" in names:
                    warnings.append(
                        f"{directory}: using AGENTS.override.md; same-directory AGENTS.md "
                        "is inactive in Codex"
                    )
                conversions.append(
                    Conversion(directory / source_name, directory / "CLAUDE.md")
                )
        else:
            if "CLAUDE.md" in names:
                conversions.append(
                    Conversion(directory / "CLAUDE.md", directory / "AGENTS.md")
                )

    if direction == "to-codex":
        rules_dir = root / ".claude" / "rules"
        if rules_dir.is_dir() and any(rules_dir.rglob("*.md")):
            warnings.append(
                f"{rules_dir}: modular/glob-scoped Claude rules were not converted; "
                "Codex has no exact equivalent"
            )
    return conversions, warnings


def write_conversion(item: Conversion, *, force: bool, dry_run: bool) -> str:
    output = rendered(item.source, item.destination)
    if item.destination.exists():
        current = item.destination.read_text(encoding="utf-8")
        if current == output:
            return "unchanged"
        if not force and not is_generated(current):
            raise RuntimeError(
                f"refusing to overwrite unmanaged file: {item.destination} "
                "(use --force after reviewing it)"
            )
    if not dry_run:
        item.destination.write_text(output, encoding="utf-8")
    return "would write" if dry_run else "wrote"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Port Markdown repository rules between Codex and Claude Code."
    )
    parser.add_argument("direction", choices=("to-claude", "to-codex"))
    parser.add_argument("root", nargs="?", default=".", type=Path)
    parser.add_argument(
        "--force", action="store_true", help="overwrite a destination not generated by this tool"
    )
    parser.add_argument("--dry-run", action="store_true", help="show changes without writing")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = args.root.resolve()
    if not root.is_dir():
        print(f"error: not a directory: {root}", file=sys.stderr)
        return 2

    conversions, warnings = discover(root, args.direction)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if not conversions:
        expected = "AGENTS.md/AGENTS.override.md" if args.direction == "to-claude" else "CLAUDE.md"
        print(f"No {expected} files found under {root}")
        return 0

    failed = False
    for item in conversions:
        try:
            status = write_conversion(item, force=args.force, dry_run=args.dry_run)
            print(f"{status}: {item.source.relative_to(root)} -> {item.destination.relative_to(root)}")
        except RuntimeError as error:
            failed = True
            print(f"error: {error}", file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
